# Dependencies
markdown:         redcarpet
highlighter:      pygments


excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Site settings
title: 'Figura i Retrat'
email: rgil@oxygen.cat
description: "L'exposició “La figura i el retrat en els fons d'art de la Fundació Iluro” es configura com  una mostra de les obres més destacades del fons."
subdescription: "La figura i el retrat en el fons d'Art de la Fundació Iluro"
duration: "Del 27 de març al 17 de Maig del 2015"
inauguration: "Inauguració, divendres 27 de març a les 19 h"
timetable: "De dimarts a dissabtes (laborables) de 17.30 a 20:00 h | Dimumenges i festius d'11:30 a 13:30 h i de 18:30 a 20:30 h | Dilluns tancat"
place: "Ateneu de la Fundació Iluro &ndash; La Riera, 92 Mataró"
baseurl:
url: "http://figurairetrat.fundacioiluro.cat"
logoWeb: /images/touch/favicon-web-128x128.png 
faviconWeb: /favicon.png
twitter_username: freecates
github_username:  freecates
twitter:          fundacioiluro

sass:
 style: compressed

author:
  name:           'Ramon Gil'
  url:            https://twitter.com/freecates

# Build settings
markdown: kramdown

#Custom vars
portfoli-author:
 name: "Figura i Retrat"
 url: http://figurairetrat.fundacioiluro.cat/
organitza:
  fundacioiluro:
    description:  "Fundació Iluro - organitzadors de Figura i Retrat"
    logo: "fundacio-iluro-organitzadors-figura-i-retrat-footer.jpg"
    url: http://www.fundacioiluro.cat/

colabora:
  artinpocket:
    description:  "Artinpocket - Partners de Figura i Retrat"
    logo: "artinpocket-partner-figura-i-retrat-footer.png"
    url:  http://www.artinpocket.cat/
  oxygen:
    description:  "Oxygen - Partners de Figura i Retrat"
    logo: "oxygen-partner-figura-i-retrat-footer.png"
    url:  http://www.oxygen.cat/

sale-end: '2014-12-31T00:00:00+01:00'

bower_components: 
  baseurl: /bower_components/
